spring:
  data:
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27017
      database: order
      authentication-database: admin
  application:
    name:
      app-process-service
  feign:
    client:
      order-service:
        url: http://localhost:8080/api/v1/orders
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: order-created-events
      properties:
        spring:
          json:
            trusted:
              packages: '*'

server:
  port: 8081